default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>
  port: <%= ENV['MYSQL_PORT'] || 3306 %>
  database: <%= ENV['MYSQL_DB'] || 'blogapp' %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default